# Generated by Django 4.2.29 on 2026-03-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
