# Generated by Django 4.2.29 on 2026-03-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
    ]
