# Generated by Django 4.2.29 on 2026-03-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserFCMToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fcm_tokens", to="accounts.user"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userfcmtoken",
            constraint=models.UniqueConstraint(fields=("user", "uid"), name="accounts_fcm_unique_user_uid"),
        ),
        migrations.AddIndex(
            model_name="userfcmtoken",
            index=models.Index(fields=["user", "is_active"], name="accounts_fcm_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="userfcmtoken",
            index=models.Index(fields=["token"], name="accounts_fcm_token_idx"),
        ),
    ]
