# Generated by Django 4.2.29 on 2026-03-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_location_post_posts_post_loc_option_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_location_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.productions'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['production_type'], name='posts_post_prod_type_idx'),
        ),
        migrations.AddIndex(
            model_name='productions',
            index=models.Index(fields=['name'], name='posts_prod_name_idx'),
        ),
    ]
