# Generated by Django 4.2.29 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_productions_remove_post_posts_post_location_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genders",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="genders",
            field=models.ManyToManyField(blank=True, related_name="posts", to="posts.genders"),
        ),
        migrations.AddIndex(
            model_name="genders",
            index=models.Index(fields=["name"], name="posts_gender_name_idx"),
        ),
    ]
