# Generated by Django 4.2.29 on 2026-04-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_genders_post_genders'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_active_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_loc_option_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_prod_type_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='about',
        ),
        migrations.RemoveField(
            model_name='post',
            name='production_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
