# Generated by Django 4.2.29 on 2026-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_posts_post_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
