# Generated by Django 4.2.29 on 2026-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='requirements',
            field=models.TextField(blank=True, help_text='Additional requirements for the post', null=True),
        ),
    ]
